### ISSUE TITLE
漫画柜下载出错

### ISSUE THREAD

**Issue by HJCFLY** [stx0821/manhuagui-autodownload#2]
![qq 20180424122034](https://user-images.githubusercontent.com/38662362/39166021-0890556c-47ba-11e8-8939-936f52253929.png)

**Comment by stx0821** [comment]
![qq 20180425162650](https://user-images.githubusercontent.com/13864505/39234309-741e0658-48a5-11e8-8135-5903adc38d29.png)
 好像是因为网站打不开了，你能打开吗

**Comment by stx0821** [comment]
已解决

**Comment by HJCFLY** [comment]
![2](https://user-images.githubusercontent.com/38662362/39244816-6de8ef4a-48c4-11e8-88a2-b47522f16d24.PNG)
还是存在这个问题

**Comment by stx0821** [comment]
是不是没拉代码，昨天我更新过了

**Comment by HJCFLY** [comment]
好的 我在试试
